### ISSUE TITLE
Arte para Entidades

### ISSUE THREAD

**Issue by Guilherme-Vianna** [Guilherme-Vianna/project-0#4]
- [x] Arte base para jogador 
- [x] Arte base para inimigo tipo 1
- [x] Arte base para inimigo tipo 2
- [x] 4 sprites simples de objetos ( Parede, Caixa, Mesa, Porta )

**Comment by GameOverReal** [comment]
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/1430dc02-36de-452c-b109-a5f2a0980955)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/64186dc6-34e7-44a9-884a-64fd185313d0)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/bf43c987-d407-45b6-aa02-735686c0c988)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/1e80a5c1-c270-40cc-84b0-7cf90c99f671)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/7f7978ee-e16b-4f1e-afc2-4c99bf265160)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/9a8c5548-89be-497a-a6eb-77d6c3bad50a)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/dbf8fdc3-2ae6-4bfd-906f-af73430297d3)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/e4316ad9-2e91-423f-b4b3-f382f41976db)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/afab1675-dc36-43ea-961d-16fd81712e9f)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/d12eedb7-c05e-453a-b6e1-00043d762354)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/d48283d7-004a-485f-8cfe-51751a8fc243)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/7ee69a81-3dfb-42b4-880e-fd1c7bbf7660)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/e928bd81-de2f-4fa5-a1cc-56fbe85b25db)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/d117a612-c060-4e6a-afc2-016e4235b059)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/19d22885-1acf-4cc0-b5d5-bcbe668cef43)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/ea66b0a4-1762-4302-a7ca-e9bece457695)
![Image](https://github.com/Guilherme-Vianna/project-0/assets/145876452/6df65303-9395-4d15-8d3f-463741e36d4c)
